name: Trivy - Escaneo de código y dependencias

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  trivy-fs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Escanear ficheros y dependencias
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          severity: 'CRITICAL,HIGH'
          scanners: 'vuln,secret,misconfig'