# SPDX-FileCopyrightText: 2026 Rubi960 & Ryosh1
#
# SPDX-License-Identifier: MIT

name: Trivy - Escaneo de imagen Docker

on:
  push:
    branches: [main, master]

jobs:
  trivy-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Build de la imagen
        run: docker build -f docker/Dockerfile -t athenapass docker/

      - name: Escanear imagen Docker
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'image'
          image-ref: 'athenapass'
          severity: 'CRITICAL,HIGH'
          scanners: 'vuln,secret,misconfig'